version: '3.8'

services:
  auth-server:
    build:
      context: .
      dockerfile: linux/Dockerfile
    container_name: auth-server
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DSN: root:gjdlmysql@2026@tcp(mysql:3306)/auth_server?charset=utf8mb4&parseTime=true&loc=UTC
      PORT: "14532"
    volumes:
      - ./installer.exe:/app/installer.exe:ro
    networks:
      - app-net

networks:
  app-net:
    external: true
